### ISSUE TITLE
using configuration manager instead of the hassel of *sh files to provision the environment 

### ISSUE THREAD

**Issue by AShabana** [RestComm/Restcomm-Connect#2709]
In this issue I propose to replace all of those huge amount of custom shell scripts with any provisioning tool , I suggest to be Ansible as it can run agentless for local deployment and I think it is the simplest .

**Comment by gsaslis** [comment]
Hi @AShabana !

Thanks for raising this issue. You're right, this is something we've been meaning to address for some time but haven't got round to it yet. 

Any contribution in this direction would be very welcome if you would like to have a go at it?

Which particular files are you referring to?

**Comment by AShabana** [comment]
The trigger of the issue that I was deploy /restcomm-connect-8-2-1 
but unfortunately get error messages from "xmlstarlet", So I decide to give a try to run restcomm with debug mode 
$ sh -x start-restcomm.sh 
and I discovered that most of the scripts is just try to write down the xml config files from the configuration parameters. I face this headache  before for managing case like this, till replace this bulk scripting effort with ansible-playbook variable files and template files,
Things become much readable and change effort reduced so much .
Let me post sample for configure ( for sure it will contain type errors and not the best practice it is just a proposal)

**/standalone/deployments/restcomm.war/WEB-INF/conf/restcomm.xml**

 using **ansible**

```
$ tree .
.
|-- site.yml                  # master playbook
|-- config
|      |-- tts.yml
|      |-- type2
|-- templates
|     |-- restcomm.xml.j2
|

```
**cat site.yml**
```
---
  - name: preparing host
    hosts: localhost
    connection: local
    vars:
         aws:
              access_key:123
         rc_home: /opt

    tasks:
    - name: Importing tts variables
       include_vars:
           file: ./config/tts.yml
           name: tts

    - name: Importing type2 variables
       include_vars:
           file: ./config/type2.yml
           name: type2

    - name: building restcomm.xml from template
        template:
           src: templates/restcomm.xml.j2
           dest: "{{ rc_home }}/standalone/deployments/restcomm.war/WEB-INF/conf/restcomm.xm"

```
 **cat templates/restcomm.xml.j2**

```
{% if tts.default == 'acapela'  %}
<speech-synthesizer active="acapela"/>
<acapela class="org.restcomm.connect.tts.acapela.AcapelaSpeechSynthesizer">
			<service-root>http://vaas.acapela-group.com/Services/Synthesizer</service-root>
			<application>{{tts.acapela.app}}</application>
			<login>{{tts.acapela.login}}</login>
			<password>{{tts.acapela.pass}}</password>
#{% for tts in tts.engines %}
# do dome loop
#{% endfor%}
{% endif %}
```
**cat config/tts.yml**

```

default: acapela
acapela:
    app: EVAL_544444
    login: EVAL_XXXXXXX
    pass: xxxxxxxx
```

to get things deployed just run

`ansible-playbook site.yml`


BTW installing ansible should be as simple as below 

```
sudo -i

if [ ! -x /usr/local/bin/ansible ]
then
        if [ -f /etc/debian_version ]
        then
                apt-get update
                apt-get install -y python-pip
        else
                yum install -y python-py
                yum install -y gcc
                yum install -y python-devel
        fi
        easy_install pip
        pip install ansible
fi
export PATH=$PATH:/usr/local/bin
ansible --version
```
